name: Format

on: pull_request

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Clang Code Formatter
        uses: ivanludvig/clang-format-action@v1.4
